### PR TITLE
Added Salesforce provider

### PR DESCRIPTION
**Pull request by genuinebasil**
Please review the Salesforce provider implementation.

### CODE REVIEW

**Comment by jerriep** [comment]
@genuinebasil Is there any specific steps one must follow when registering the app in SalesForce? I went through the default steps, but get errors during authentication process.

I you could perhaps screenshots of how your app is configured in SalesForce is will help a lot. Just make sure you blur out sensitive details such as your app key and secret :)

**Comment by jerriep** [comment]
@genuinebasil I am going to delete the SalesForce provider for now as I cannot get it working and I need to do a new release of the package. Please reply with details with how to configure an app in SalesForce.

**Comment by genuinebasil** [comment]
Hi Jerrie,

Please accept my apologies for late reply. Please find the steps to setup a developer salesforce account and connected app here - https://www.dropbox.com/s/6eb6spen5tz6c5v/Salesforce-Connected%20App%20Settings.docx?dl=0

Please email me directly to genuinebasil@gmail.com, if you need any more information.

Regards,
Genuine

**Comment by jerriep** [comment]
No worries. The thing that tripped me up was that the callback URL had to be SSL. I have written a detailed guide which is available at http://beabigrockstar.com/guides/aspnet-oauth/aspnet-mvc-salesforce-login

**Comment by jerriep** [comment]
@genuinebasil We are looking for help moving to ASP.NET 5. Please read http://www.jerriepelser.com/blog/calling-contributors-for-oauth-providers

**Pull request merged**
