### PR TITLE
Instagram provider

### PR DESCRIPTION
**Pull request by jokcofbut**
New Instagram provider based on http://instagram.com/developer/authentication/

### CODE REVIEW

**Comment by jerriep** [comment]
Thank you @jokcofbut !

**Comment by bnurbekov** [comment]
Hi. I have a question regarding this provider. Have you tried to test your implementation? This provider always gives me the following error: {"code": 400, "error_type": "OAuthException", "error_message": "Redirect URI does not match registered             redirect URI"}. 
I use http://localhost:44302/Account/ExternalLoginCallback as a callback url. 
I suppose this issue might be caused because of the returnUrl parameter that is passed by ExternalLogin() method of Microsoft Identity 2.0 Framework. Any ideas on how to resolve this issue? Thank you in advance!

**Comment by jerriep** [comment]
That redirect URI is not correct.  Try setting it to http://localhost:44302/signin-instagram

**Comment by bnurbekov** [comment]
Thank you very much for this suggestion! It worked.

**Comment by jerriep** [comment]
@jokcofbut We are looking for help moving to ASP.NET 5. Please read http://www.jerriepelser.com/blog/calling-contributors-for-oauth-providers

**Pull request merged**
