### PR TITLE
Added Reddit authentication option

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by jerriep** [comment]
Thank you so much for your contribution @josephyanks.  I will try and get this in and release a new Nuget package over the weekend.

**Comment by ghost** [comment]
Hey Jerrie-

So it appears that the reddit authentication works well, but it makes me re-allow the app every single time that I log in rather than using the permanent token (also, not sure how to go about using a refresh token either...). Any ideas on why I can't keep myself logged in? Have you run into that with the other providers?

**Comment by jerriep** [comment]
@josephyanks That is standard behaviour for all OAuth logins using the default templates.  To make them persistent find the calls to `SignInAsync()` in your `AccountController` and make sure you set the `isPersistent`  parameter to `true`

**Comment by jerriep** [comment]
@josephyanks We are looking for help moving to ASP.NET 5. Please read http://www.jerriepelser.com/blog/calling-contributors-for-oauth-providers

**Pull request merged**
