### PR TITLE
Adding StackExchange

### PR DESCRIPTION
**Pull request by ghost**
I have added support for StackExchange. Details on StackExchange OAuth2.0 authentication can be found here - http://api.stackexchange.com/docs/authentication. 

Note: 
1.StackExchange provides a "key" in addition to client_id and client_secret. This seems to be a mandatory parameter for the /me API(user info API) in addition to the access_token.

2.Empty scope is enough to get basic user information from the /me API. For other information scope can be set to read_inbox, no_expiry, write_access and private_info(see the authentication doc above).

### CODE REVIEW

**Comment by jerriep** [comment]
Thank you @payojbaral , all looks fine. I will test and integrate it tomorrow

**Comment by ghost** [comment]
Sounds good. Thanks.

**Comment by jerriep** [comment]
Thank you @payojbaral . Version 1.6.0 now available on the Nuget gallery

**Comment by ghost** [comment]
Oh awesome. Thank you very much. 

Regards
Payoj

**Comment by jerriep** [comment]
@payojbaral We are looking for help moving to ASP.NET 5. Please read http://www.jerriepelser.com/blog/calling-contributors-for-oauth-providers

**Pull request closed without merging**
