### PR TITLE
introduce Azure Active Directory OAuth provider

### PR DESCRIPTION
**Pull request by stefann42**
Azure AD is used by Office 365 tenants and supports authenticating users
using OAuth. So if you want to build Office 365 (Mail, Calendar,
Contacts) apps you can use this provider to authenticate users (your
tenant or multi-tenant). I'm using this for www.FreeBusy.io

### CODE REVIEW

**Comment by jerriep** [comment]
Stefan, thanks for your contribution but can you please remove the licensing portion from each file. 

The entire library is under MIT license - which I was never explicit about and has now added.

**Comment by stefann42** [comment]
I can certainly change the license notice from Apache to MIT. How would you like to credit contributors? I believe that at the very least whomever writes a complete provider like ArcGIS, Battle.net or in my case AzureAD is entitled to put their name on the copyright line which means the notice should be repeated at the top of the source file. (After all, folks contributing a full provider have the option of publishing the provider under their own project). Let me know and I'll adjust on my side. Thanks.

**Comment by jerriep** [comment]
@stefann42 I have always been more than open about thanking contributors. I do so in the release notes of the Nuget package (http://www.nuget.org/packages/Owin.Security.Providers/) and I also thank contributors on Twitter every time I release a new versions of the Nuget package.

There should probably be a more central place to list all contributors so I will add it to the project's readme file on Github (I will look into it sometime this week...)

That being said I do not want separate licensing and copyright notices in files. If that is not acceptable your are more than welcome to publish it under your own separate Nuget package.

Let me know how you wish to proceed

**Comment by stefann42** [comment]
I understand your preference about not burdening the source files with license notices and I like that cleanliness myself. However I think you should list major (per the definition above) contributors in the license file at least by name if not with attribution of their specific provider.

**Comment by jerriep** [comment]
Do you have an example of how other projects handle it this way? 

I have looked at my projects and have never seen them list contributors in the license file. Many does have a separate section in the readme file to list all contributors, and that I will do.

**Comment by stefann42** [comment]
I think traditions and standards are yet to be established for the wide variety of contribution types we're seeing on GitHub and elsewhere. I did some research I wasn't able to find a standardized practice for contributing related stand alone components to a larger project for the sake of packaging as one unit.

The more typical case is an incremental (i.e. new feature) contribution to an open source library in which case I believe the original library author remain the main copyright holder and credits can be given in the a README. For instance, I added some features to https://github.com/VinceG/twitter-bootstrap-wizard,  my name doesn't appear anywhere in the project, and I don't mind that. 

In this case however I'm contributing to your project a self-sufficient component implemented to a standard interface that Microsoft defined. It doesn't depend on, nor is it an incremental improvement to your original submission (I'm not adding features to your LinkedIn provider for ex). I submitted the pull request for the convenience of having the AzureAD provider packaged together with your other providers. 

I believe this situation is more akin to folks contributing a driver to the Linux Kernel codebase and in those case each driver is clearly attributed to its author. BTW, I think it's great that you started this project, and I'd like to see all providers eventually make their way into Microsoft's Katana project, but we may have to wait another year for everyone there to catch on to the new mentality :).

**Comment by jerriep** [comment]
I have added a section to the readme with the contributors listed explicitely. If you would like to still contribute then please update pull request by removing licensing sections in files and resubmit.

As far as the future of this project is concerned, it does not seem bright. First of all the security components are moved from Katana into ASP.NET (https://github.com/aspnet/Security).

Secondly I reached out to MS to see how these current providers could be integrated into that project. The thing is that with ASP.NET 5 Microsoft has added a very generic OAuth provider which could basically connect to most OAuth services with simple configuration, so this library in its current state will not be required anymore in most instances for anyone using ASP.NET 5

**Comment by stefann42** [comment]
Thanks for moving on this, however, due to unrelated circumstances I decided to create a separate repository for this particular provider so it's now at https://github.com/BizLogr/AzureAD-OAuth-Provider. Just curious, why do you prefer MIT License? I chose Apache only because that's what Katana uses.

Interesting direction for ASP.NET 5. I suspect the config for the generic OAuth provider will become as large as a AuthenticationHandler in the current model. Unfortunately there are many variations in OAuth implementations and it's actually the reason I started a dedicated discussion with the Office 365 and Azure AD teams. In their case they decided to forgo completely the Scope parameter and they introduced a Resource parameter. I wonder how that config will look like in ASP.NET 5 :).

**Comment by jerriep** [comment]
No problem :)

No particular reason on the license. It is just the go to license for all the open source stuff I do and suffices for my needs. I basically want to allow people to do with it as they please.

In terms of the future of Katana, you may also want to read this:
http://blogs.msdn.com/b/webdev/archive/2014/11/14/katana-asp-net-5-and-bridging-the-gap.aspx

**Comment by jerriep** [comment]
@stefann42 We are looking for help moving to ASP.NET 5. Please read http://www.jerriepelser.com/blog/calling-contributors-for-oauth-providers

**Comment by stefann42** [comment]
Saw your email, good call. Glad to contribute when we'll move our web app to ASP.NET 5 (probably next year).

**Pull request closed without merging**
