### PR TITLE
Add Google Sign-In provider

### PR DESCRIPTION
**Pull request by gwilymatgearset**
As mentioned in https://github.com/TerribleDev/OwinOAuthProviders/issues/249, Google+ authentication is being deprecated soon (and requests have already started to fail intermittently from the 28th of January). Source: https://developers.google.com/+/api-shutdown

This implements the Google Sign-In authentication as explained in their migration guide.

Implementation notes:

1. Mostly a copy from the old GooglePlus sign in. Left the old one in because it could still be useful to people while they migrate.
2. Needed to use a different method of collecting email, unique id etc. The TODO can be done at a later time.
3. From my testing, it seems that user ids are kept the same between Google and GooglePlus which is a relief.

### CODE REVIEW

**Comment by gwilymatgearset** [comment]
@TerribleDev Would you mind having a look?

**Comment by TerribleDev** [comment]
@gwilymatgearset Hey, so sorry I didn't see this. I have to pick up my wife from the airport today, i'll try to get to this tomorrow-ish.

**Comment by gwilymatgearset** [comment]
@TerribleDev Hope you had a safe trip. Did you get a chance to look?

**Comment by TerribleDev** [comment]
lgtm

**Comment by TerribleDev** [comment]
thanks for doing this!

**Comment by TerribleDev** [comment]
And thanks for dealing with my ever busier schedule

**Pull request merged**
